### ISSUE TITLE
Error codes utf-8

### ISSUE THREAD

**Issue by janhoffmann81** [bundestag/gesetze-tools#10]
python lawde.py loadall
Laws to download: 6420
0.0%
Traceback (most recent call last):
  File "lawde.py", line 175, in <module>
    main(arguments)
  File "lawde.py", line 168, in main
    lawde.loadall()
  File "lawde.py", line 128, in loadall
    self.load(self.get_all_laws())
  File "lawde.py", line 90, in load
    self.store(law, zipfile)
  File "lawde.py", line 109, in store
    dom = parseString(xml.decode('utf-8'))
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 475: ordinal not in range(128)

**Comment by stefanw** [comment]
I just pushed a commit which should add Python3 support. Use Python3.
